### ISSUE TITLE
The Live section should have a "Toggle number on filename" button, which either adds a 5 digit number or removes it from the filename. Example: Exam-2016.pdf becomes Exam-2016-65334.pdf. The purpose is to avoid easy guessing of filenames.

### ISSUE THREAD

**Issue by iainbryson** [dtu-compute/file-manager#4]

**Comment by dtu-compute** [comment]
I am closing as this is from the old spec. The live/pending shouldn't be needed.

The new spec is

https://github.com/dtu-compute/doc/blob/master/file-admin-as-gem.md

where we should wait implementing the Sharelatex part for now.
